[package]
name = "connect_four"
version = "0.1.0"
authors = ["Morasiu <morasiu2@gmail.com>"]

[dependencies]
getch = "0.2.0"
console = "0.6.1"

[[bin]]
name = "connect_four"
path = "src/connect_four.rs"